### ISSUE TITLE
Regarding Communication and Collaboration

### ISSUE THREAD

**Issue by elopez3** [TobiasMue91/tobiasmue91.github.io#1]
Hello Tobias, do you have a preferred communication method? If yes, kindly let me know. I'm interested in discussing your research on the top-p and temperature tools. My Discord username is "realgavok". Working together would be worth it, and I am proactive in creating better solutions. Thank you for your time, and I hope to receive your response soon.

**Comment by TobiasMue91** [comment]
Hi @elopez3, Thank you for reaching out! I'm glad to hear you're interested in my project. My preferred communication medium is email. Feel free to share your collaboration ideas at `tobias.mue91@googlemail.com`. I look forward to hearing from you!
